### ISSUE TITLE
Instância não possui tipagem

### ISSUE THREAD

**Issue by 4lessandrodev** [efipay/sdk-typescript-apis-efi#4]
## Ao criar uma nova instância as tipagens dos métodos não estão disponíveis:

Versões: 

sdk-typescript-apis-efi@1.0.2

nodejs v20.10.0

![image](https://github.com/efipay/sdk-typescript-apis-efi/assets/34426407/15c909c8-6cbe-4abd-a94d-e44487aa6ce3)

**Comment by joao-muniz-efi** [comment]
Olá @4lessandrodev, espero que esteja bem.
Informamos que na versão 1.2.0 foi implementado a tipagem na instância da classe.
Essencialmente recomendamos que migre para o https://github.com/efipay/sdk-node-apis-efi que agora é compatível com TS, em breve o pacote sdk-typescript-apis-efi não receberá mais atualizações, tendo em vista que é possível utilizar o sdk-node-apis-efi em TypeScript.
