### ISSUE TITLE
endpoint de boleto

### ISSUE THREAD

**Issue by LucasSaud** [efipay/sdk-typescript-apis-efi#5]
é possivel solicitar um boleto por endpoint e receber o pdf do boleto? se sim, é possivel encontrar o boleto pelo cpf_cnpj do pagador?

**Comment by joao-muniz-efi** [comment]
Bom dia, @LucasSaud. Espero que esteja bem.
Sim, ao criar um boleto você terá acesso ao PDF dele, você pode executar [este exemplo](https://github.com/efipay/sdk-typescript-apis-efi/blob/main/examples/charges/billet/createOneStepBillet.ts) para ver os campos retornados na criação de uma cobrança. Também é possível buscar cobranças pelo documento do devedor, utilize [este exemplo](https://github.com/efipay/sdk-typescript-apis-efi/blob/main/examples/charges/billet/listBillets.ts) e o campo `customer_document` para enviar o documento, assim você terá como retorno as cobranças que foram emitidas para o documento buscado.

Salientamos que reservamos as Issues aqui do GitHub somente para questões diretamente ligadas ao SDK em questão.
Para dúvidas como essa pedimos que entre em contato com a gente através da nossa comunidade no Discord, https://comunidade.sejaefi.com.br/.  😊
